networks:
  default:
    name: docker-default-network

services:
    database:
        build:
          context: db-init      
        container_name: "super-database"
        ports:
            - "5432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        
    monitoring:
        build:
          context: monitoring
        container_name: "super-visor"
        ports:
          - 9090:9090

    kafka:
        image: vectorized/redpanda:v22.1.7
        command:
        - redpanda
        - start
        - --smp
        - '1'
        - --reserve-memory
        - 0M
        - --overprovisioned
        - --node-id
        - '0'
        - --kafka-addr
        - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        - --advertise-kafka-addr
        - PLAINTEXT://kafka:29092,OUTSIDE://kafka:9092

    kafdrop:
        image: obsidiandynamics/kafdrop
        ports:
          - "9000:9000"
        environment:
          KAFKA_BROKERCONNECT: "kafka:29092"
          JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        labels:
          - 'traefik.enable=true'
          - 'traefik.http.routers.kafdrop.rule=Host(`kafdrop.localhost.direct`)'
          - 'traefik.http.routers.kafdrop.entrypoints=web,websecure'
        depends_on:
          - "kafka"
        
    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - 9008:80